In [4]:
import pandas as pd
df1 = pd.read_csv('youtube_test_en.csv')
df2 = pd.read_csv('youtube_train_en.csv')
df3 = pd.read_csv('youtube_val_en.csv')

In [5]:
df1[["text", "text_en"]].sample(20)

,text,text_en
129,रवीन्द्र मिश्र सर जस्तो सोज विचार भए को नेता ह...,If such a leader as Raveendra Misra Sir had be...
168,झोले हरु काम छैन बिथा मा विभिन्न कुरा गर्छन या...,"The bags don't work, they talk about things di..."
236,बेइमानी गधा रबिन्द्र अधिकारी त निर्देशन पालक द...,The unfaithful ass Rabindra is the officer and...
65,यसरी नै अधि बढ्नु ।,This is how you grow.
237,नारायण सर हजुर जस्तो मान्छे नेपाल का लागि नेपा...,A person like Narayan Sir Hajhur had to come t...
8,पुलिस ले त जहिलेनि झुट बोल्छ साला ज्ञानेन्द्र ...,"The police take it as often as he lies, Sala G..."
9,हामी नेपाली हरुलाइ यस्तो ज्यान मारा नेपाल प्रह...,We Nepalese people are the kind of people who ...
194,साला भिकारी हरु तिम्रा बाउ भन्दा पनि ठूलो होला ।,The Sala beggars were greater than your father.
193,यो डकैती गर्ने सहकारी लाई चाडो कारवाही होस राम...,This robbery partner needs to be punished by t...
233,यो Dig ले पही ले नै माओवादी को गोलि खानु पर्ने...,It is only after Dig takes over that Maoist is...
27,शेरे बोल्छनै तेस्तै पत नपाउदा मुर्छा परेछ साला...,"The lion speaks like a dead man, but not a dea..."
215,बौलाएर भालु बरबराएर नांगै हिडीछे र पार्टी ले न...,The bear was barbaric and barefoot and walked ...
199,यो रन्डी सावित्री लाई Dna तेस्त गर यो पनो छक्क...,This Randy Savitri is a Dna Teest if it is a P...
72,सिधा कुरा जनता सग हेर्दा अलिकति गलत नियत भए जस...,If the public were to see the whole thing as a...
112,दुबै जना लाई सङ्गै राखेर अन्तरबार्ता लिनु पर्यो ।,Both men had to be kept together and interacted.
130,"सहि कुरो मेयर जु , छोडनु हुदैन भ्रष्ट दलाल झोल...","Sahi kurō Mayor Ju , do not leave corrupt brok..."
157,गोलि किन हान्यो तिर्थ लाइ प्रहरी ले त चोर होश ...,The thief was a wise prophet when the guards t...
42,देस को धमिरा किरा हरु ले देस लाई खोक्रो पारे ।,The country was destroyed by the earthquakes.
139,"सबै जल , जमीन , जंगल पूर्णरुपम राष्ट्रीयकारण ग...","All water, land, forest, and nationalist cause..."
118,बिचरा चीन को राश्ट्रपती नेपाल सबै तिर यतिकओ रा...,China must have been confused by the fact that...

In [6]:
df2[["text", "text_en"]].sample(20)

,text,text_en
970,तिमी हरु सबै चोर लाई चाक बाट गोलि हानी मुख बाट...,"You must get all thieves out of the way, now t..."
104,पुण्य झोले मुदाबाद केपी र प्रचण्डे को झोले कुक...,The good bags are buttered KP and the bad bags...
957,"रन्डि का भ्रस्ट छोरा हरु , कति लुट्छौ ?","Randy's corrupt sons , how much do you rob ?"
507,रामकृष्ण सर जस्तो मान्छे लाई तेस्तो गर्ने हावा...,The air system that does such things to a pers...
155,यो कुकुर को छाऊरो ले गलत भन्दैछ यो कुकुर भने क...,This dog is a dog that is unemployed and is no...
1059,रबि सर यदि मिल्छ भने DR भिमार्जुन अाचार्य लाई ...,"Rabi Sir, if you can find Dr. Bhimarjun Achary..."
1023,यो मुला canada nepal chanel का थियो जब चितवन म...,But it was the canada nepal channel when the m...
479,"रवि दाई पृथ्वी को सतह हुन , तिन करोड नेपाली oz...","Ravi said the Earth is a surface, three millio..."
1152,राजेश हमाल दाइ कता जानू भएछ ?,How did Rajesh Hamal Dai know about this?
377,एउ टा प्रहरी को प्रबकता ले घरि घरि झुट बोल्नु ...,It is not right to lie to a police officer in ...
953,चालक सहचालक पनि अलि योग्य सभ्य र पढेलेखे का ला...,The co-driver should also wear a slightly dece...
1124,पाहुना को स्वागत भब्य रुप मा गरौ जय नेपाल ।,The guest is warmly welcomed to Garoo Jai Nepal.
271,यदि यस्तै पारा हो भने त्यों दिन आउन बेर लाग्दै...,"If so, then the day will soon come when the pe..."
370,प्रत्रकार ज्यु ले प्रश्न सोधे को भयेन .. अध्यन...,"For example, Jews are afraid to ask questions,..."
1156,अब को प्रधानमन्त्री रबि सर नेइ हुनुपर्छ योनेई ...,"The Prime Minister, Rabin Sir Ney, must now be..."
849,सोम प्रसाद पाण्डे को चाहीं गर्धन भाचीने गरी हा...,Som Prasad Pandey wants to lead the Serbhara B...
1008,अब सिधाकुरा कार्यक्रम हैन रवि दाजु देश चलाउनु ...,Now the Sidhakur program is not run by Ravi Da...
123,यो अहिले को ब्यबस्था भन्दा राजसस्था उत्तम छ !,It is now better to have a monarchy than a gov...
26,थुक्क चुतिया हरु हो लाज सरम छैन दुबै जना चुतिय...,Both of them are not ashamed of corruption.
693,सुशील सर लाई देखे पछि उहाँ को कार्यक्रम नहेरी ...,"After seeing Sushil Sir , he does not feel sle..."

In [7]:
df3[["text", "text_en"]].sample(20)

,text,text_en
122,बालुवाटार काे जग्गा त हडपेकाे छ गुठि त्यसै छाे...,The sandy sandy beaches and the six bones are ...
183,रबिन्द्र दाई लाई राजनीतिज्ञ हरु ले मारे को महस...,Rabindra Daye is feared by politicians to be k...
163,चितवन प्रशासन होटल कङ्गारु को मालिक लाई समातेर...,The administration of the hotel catches Kangar...
47,अपराधी डाँका हरु ले स्वर्ग को सपना देखाएर किन ...,The ghost under his waist was apparent when he...
135,"कसै ले कसै लाई आरोप , प्रत्यारोप गर्नु पर्दैन ...","No one should be accused of murder, no one sho..."
49,नत्र आज यति ठुला ठुला मान्छे लाई गुमाउनु पर्ने...,"Today, such a big man should not have to lose."
174,पत्रकार र पत्रकारिता ले नेपाली समाज को रुपान्त...,Journalism and journalism can transform Nepali...
52,चितवन प्रशासन होटल कङ्गारु को मालिक लाई समातेर...,The administration of the hotel catches Kangar...
33,रबिन्द्र सर को आवाज मा केही जोस दम छ अब को आश ...,Rabindra Sir's voice has a little bit of enthu...
243,सङ्घियता तथा गणतन्त्र ले देश खाेक्राे पार्याे ।,The country has been divided between federatio...
235,राडी रन्डी बौलायो आफु राम्रो भ को भए ४ चोती है...,"Randy Randi was a fool who, for his own good, ..."
190,सलाम छ गगन थापा ज्यु यसरि नै राम्रो काम गर्दै ...,"Salaam is the heaven of the Jews, and know tha..."
154,भ्रष्टाचर को मुद्दा मा नेता हरु संग कार्यक्रम ...,A program with leaders on the issue of corrupt...
81,sabitri ko mukhma mutideu dhamala ji. ... ।,sabitri ko mukhma mutideu dhamala ji. ... . . ...
129,यो पन्ने मुजिलाइ ब्रेनवास गर्नकोलागि राडिकाछोर...,This page is dedicated to the brain-brain tran...
43,तपाई हरू पनि त किन एउटै प्रश्न साेध्नु हुन्छ त...,"You also ask the same question, and you agree ..."
86,फलाम ताते बेला मा साइज मा ल्याउने काम गर्नुस ।,Do the work of bringing the iron into the size...
160,"हामी ३ करोड नेपाली लाई अखण्ड , येक ढिक् का नेप...","We three crore Nepalese people have to be one,..."
97,साह्रै मातिन थाले यी so called communist हरु ।,The so-called communists were very much involved.
113,राजेन्द्र जी तपाई मेयर लाई आक्रमण मा नऊत्रनु ह...,"Rajeendra Ji, you must not attack the mayor be..."