In [1]:
import pandas as pd

df1 = pd.read_csv('twitter_test_en.csv')
df2 = pd.read_csv('twitter_train_en.csv')
df3 = pd.read_csv('twitter_val_en.csv')

In [2]:
df1[["text", "text_en"]].sample(20)

,text,text_en
549,सुदूरपश्चिम प्रदेशका मन्त्रीहरूले एक महीनाको प...,Ministers from the Far West are to collect a m...
211,सम्माननिय ज्यू तपाईको कुरा सबै पत्यायौ र समर्थ...,"Respectful Jews, I know all about you and I su..."
4512,कोभिड काठमाडौँमा बजार खोल्न नदिने सरकारी निर्णय,The government decision not to open the market...
1669,कोरोना भाइरस कोभिड को परीक्षण र उपचार आफ्नै खर...,The coronavirus Covid testing and treatment ha...
1705,कोभिड निको हुन कति समय लाग्छ,How long does it take to recover from COVID?
4933,भारतमा कोभिड बाट एकै दिन झण्डै हजार सङ्क्रमित,India has almost a thousand cases of Covid in ...
1253,कोभिड कोरोना रोकथामका लागि मेडिकल सामान बोकेर ...,Sudip Puri landing a Nepali army sky truck car...
865,कोभिड को संक्रमणको त्रासले काठमाडौं उपत्यकाबाट...,The crisis of COVID infection has increased tr...
851,कोरोना भाइरस कोभिड फैलिएपछि चीनबाट स्वदेश फर्क...,Nepali students who returned from China after ...
1739,कोभिड बीपी प्रतिष्ठानमा उपचाररत झापाका संक्रमि...,Death of a man infected with Jaffa being treat...
2063,ईस्लाम धर्मावलम्बीहरुको पवित्र महिना रमजानको प...,"On the holy month of Ramadan, which is the Isl..."
2399,स्वास्थ्य मन्त्रालयको कोभिड प्रेस बिफ्रिङ दैनि...,The Health Ministry's COVID press briefing sho...
2906,यतिखेर कोभिड भ्याक्सिनको परीक्षण त्यसले काम गर...,"So far, testing of a COVID vaccine has been do..."
1128,कोरोना भाइरस खोप कोभिड विरुद्ध विकसित अर्को खो...,"The coronavirus vaccine, another vaccine devel..."
1236,विश्व भरी जो जहाँ छ त्यो त्यही सेल्फ क्वारेन्ट...,"The world is wherever it is, the best way to a..."
508,कोभिड रोकथाम तथा नियन्त्रण उच्चस्तरीय समन्वय स...,The meeting of the High-Level Coordination Com...
4912,पछिल्लो समयमा कोभिड संक्रमण दर महिलामा बढेको छ...,"In recent times, the rate of COVID infection a..."
4664,कोभिड को खोप किन्न सजिलो औषधि तेस्रो संशोधन अध...,The third amendment to the ordinance issued a ...
3262,भारतमा कोभिड संक्रमित लाख हजार नाघे लाख हजार भ...,"In India, COVID infections have killed more th..."
219,कोभिड अपडेट बेलुका नयाँ संक्रमित जना यो संगै ज...,The COVID update in the evening has resulted i...

In [3]:
df2[["text", "text_en"]].sample(20)

,text,text_en
19986,के आइलाग्यो बरीलै सिम्टोम त कोभिड सँग मिल्छ त,If the symptoms of Ilagyo barile are combined ...
14802,घण्टाभित्र ललितपुरमा कोभिड संक्रमित तीन जनाको ...,"Within an hour, three people infected with COV..."
10155,ले कोरोना भाईरस कोभिड को संक्रमण रोकथाम तथा नि...,Le Coronavirus COVID infection prevention and ...
19846,टोल टोलमा पढाउँदै शिक्षक कोरोना भाइरस कोभिड सङ...,"Teachers teaching in a toll tolling school, te..."
13114,कोभिड संग लडन सक्ने हिम्मत र साहस संगै हामी जि...,"With the courage and courage to fight COVID, w..."
13769,कोभिड महामारीविरुद्धको लडाइँमा भारतले नेपाललाई...,India has given further support to Nepal in th...
1952,कोभिड ले विश्वकै आर्थिक वृद्धिमा असर पर्नसक्छ ...,COVID could affect global economic growth at t...
12030,कोभिड को समस्य समाधान को लागि लडाइँमा उहाँ को ...,He has been a part of the fight for the soluti...
17572,कोभिड को जोखिमलाई दृष्टिगत गरी अझै दुई महिना श...,"In view of the risk of COVID, the government h..."
15868,आफैं कोभिड को नमूना परीक्षण गराउन रू हजार लाग्ने,"It will take Rs 1,000 to get a sample test of ..."
21348,भारतमा पछिल्लो घण्टामा कोरोना भाइरस कोभिड का ह...,A thousand new cases of coronavirus COVID-19 h...
4749,नेपालमा प्रतिशतलाई कोभिड खोप दिइने तयारी,A percentage of Nepal's population is preparin...
9271,आगामी वर्षको बजेट कोभिड को प्रभाव न्यूनीकरणमा ...,The budget for the coming year is based on mit...
14903,कोरोनाभाइरस कोभिड प्रकोप फैलिएको चीनको वुहानबा...,Four things you should know about the plan to ...
1613,युवा पनि कोभिड को उच्च जोखिममा डब्लूएचओ,Even young people are at high risk of COVID.
3154,वीरगञ्जको विशेष कोरोना अस्पतालबाट कोरोना भाइरस...,"Today, after defeating the coronavirus Covid i..."
12232,कोभीड को कारनले लानै मानेन हुलाक अफिस ले,The post office has denied that COVID was caus...
18770,वीर अस्पतालबाट प्रवाह हुने प्रकारका सेवा सेवाग...,The service is provided to the patient from ho...
21105,यहि समयमा दक्षिण सिमानामा पुरै घेर्न पाए यो को...,"At the same time, it could have been completel..."
4907,भारतमा हाल दैनिक दुई लाख कोभिड नमूना परीक्षण ग...,ICMR said that India currently has the capacit...

In [4]:
df3[["text", "text_en"]].sample(20)

,text,text_en
4370,कोभिड को खोप निर्माण युद्धमा चीन सबैभन्दा अगाडि,China is at the forefront of the COVID vaccine...
926,अबको केहि दिन टियलमा कोरोना कोभिड जस्ता शब्द प...,"For a few days now, Tialma decided not to use ..."
508,कोभिड महामारी नियन्त्रण न सरकारको एक्लो प्रयास...,COVID pandemic control is not possible by gove...
1701,लामखुट्टेले टोक्दा डेङ्गु कुकुरले टोक्दा रेबिज...,"Mosquitoes, tocked dengue dogs, tocked rabies,..."
9,सरकारले यो सातादेखि उपत्यकाबाहिरका सात स्थानमा...,The government has since extended testing of C...
2553,कोभिड अन्त्यको अनिश्चितताका बेला इन्टरनेटको आव...,While the need for the internet has become wid...
2966,औं विश् व स्वास्थ्य महासभालाई आज बिहान सम्बोधन...,Addressing the World Health Assembly this morn...
3095,स्वास्थ्य तथा जनसंख्या मन्त्रालयले कोभिड एन्टि...,The Ministry of Health and Population has set ...
3912,कोभिड बाट नेपालमा कुल जना संक्रमित,The total number of people infected with COVID...
4131,दिल्लीमा आइतबार कोभिड सङ्क्रमितभन्दा निको हुने...,Delhi has a higher number of recovery cases th...
3687,आलोचना भएपछि सरकारले नयाँ नियम ल्याएछ स्वघोषणा...,"Following criticism, the government has introd..."
2800,कोभिड को असर चुनौती तथा अवसर,The impact of COVID on the challenges and oppo...
1239,कोसी अस्पतालको कोभिड उपचार केन्द्रमा थप कोरोना...,More coronavirus-infected discharges have take...
511,संसारको तीब्र कम्प्युटरले पहिचान गर्यो कोभिड व...,The world's fastest computer has identified po...
3581,ए बिबेक सुन्य ख्वामित बढाएर मात्र कोभिड कन्ट्र...,A baby's ear is controlled only by increasing ...
2292,कोभिड ले निको पार्छ भन्ने न्यूज भाइरल भइरहेको ...,"News that COVID is curing is going viral, bewa..."
2097,धरानस्थित बीपी कोइराला स्वास्थ्य विज्ञान प्रति...,"A three-year-old woman from Morong, who was be..."
1473,म स्वास्थकर्मी होईन तर एउटा कुरो चाहिँ लेख्न म...,"If I am not a healthcare worker, I wanted to w..."
3851,नयाँ कोभिड महामारी यमनजस्तो द्वन्द्वग्रस्त मुल...,A new COVID pandemic will prove to be a more a...
2034,कमाउनिष्ट सरकार कोभिड ब्यक्सिन पिस रुसले नेपाल...,The communist government is trying to get a wh...